[package]
name = "smwc_spc_dl"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]

[dependencies]
failure = "0.1.2"
reqwest = "0.9.1"
serde = "1.0.79"
serde_derive = "1.0.79"
base64 = "0.9.3"
